### ISSUE TITLE
Click succeeded but Load Failed

### ISSUE THREAD

**Issue by ipmonline** [aeberhardo/phantomjs-linux-armv6l#10]
Raspbian GNU/Linux 7
Selenium 2.43.0

```
Traceback (most recent call last):
  File "./script.py", line 35, in <module>
    w.find_element_by_css_selector("#re%s a" % id_name).click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 65, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 385, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: u'Error Message => \'Click succeeded but Load Failed. Status: \'fail\'\'\n caused by Request => {"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"81","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:60444","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\\"sessionId\\": \\"f9657870-4f8c-11e4-aa77-3792b3031674\\", \\"id\\": \\":wdc:1412842773694\\"}","url":"/click","urlParsed":{"anchor":"","query":"","file":"click","directory":"/","path":"/click","relative":"/click","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/click","queryKey":{},"chunks":["click"]},"urlOriginal":"/session/f9657870-4f8c-11e4-aa77-3792b3031674/element/%3Awdc%3A1412842773694/click"}' ; Screenshot: available via screen
```

**Comment by nanderh** [comment]
This repo has version 1.9.0 and this is a known issue: https://github.com/ariya/phantomjs/issues/11443
Try your same code with one of the binaries from here (They're not stable though): https://github.com/nanderh/phantomjs-linux-armv6l
See if the error is still there.

**Comment by ipmonline** [comment]
The phantomjs v1.10.0 (development) 03062014 solves my issue.

Thank you very much.
